const demo={football:[{league:'Free fallback',time:'—',home:'Ожидание реальных событий',away:'источник подключается',score:'–',status:'DATA',odds:[],pass:null,market:'REAL DATA',value:null}],tennis:[],hockey:[],basketball:[],mma:[]};
const ESPN={football:'soccer/eng.1',basketball:'basketball/nba',hockey:'hockey/nhl',tennis:'tennis/atp',mma:'mma/ufc'};
const TSB={football:'Soccer',basketball:'Basketball',hockey:'Ice Hockey',tennis:'Tennis'};
const SPORT_SCORE={football:'football',basketball:'basketball',tennis:'tennis'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const requestedSport=new URLSearchParams(location.search).get('sport');
let active=['football','tennis','hockey','basketball','mma'].includes(requestedSport)?requestedSport:'all',remoteEvents=[],authMode='login';
function allEvents(){const base=remoteEvents.length?remoteEvents:Object.entries(demo).flatMap(([sport,items])=>items.map(x=>({...x,sport})));return active==='all'?base:base.filter(x=>x.sport===active)}
function matchUrl(x){const p=new URLSearchParams({home:x.home||'',away:x.away||'',score:x.score||'– : –',time:x.time||'—',league:x.league||'VIKA SPORTS',sport:x.sport||'sport',status:x.status||'PRE'});if(x.eventId)p.set('eventId',x.eventId);if(x.source)p.set('source',x.source);return 'match.html?'+p.toString()}
function card(x){const live=x.status==='LIVE';const pass=x.pass==null?'—':x.pass+'%';const value=x.value==null?'—':'+'+x.value+'%';return `<article class="event ${live?'is-live':''}"><div class="event-head"><span>${live?'🔴 LIVE':x.status==='FINAL'?'✓ FINAL':'🕒 '+(x.time||'—')}</span><small>${x.league||''}</small></div><div class="teams"><div><b>${x.home}</b><small>${x.odds?.[0]||''}</small></div><div class="score">${x.score||'–'}</div><div class="away"><b>${x.away}</b><small>${x.odds?.[1]||''}</small></div></div><div class="chips"><span>${x.market||'Матч'}</span><span>Pass <b>${pass}</b></span>${x.value!=null?`<span class="value">Value ${value}</span>`:''}</div><div class="event-foot"><span>${x.source||'Источник данных'}</span><a href="${matchUrl(x)}">Анализ →</a></div></article>`}
function render(){const box=$('#events');if(!box)return;const arr=allEvents();box.innerHTML=arr.map(card).join('');const count=$('#count');if(count)count.textContent=arr.length;const mirror=$('#countMirror');if(mirror)mirror.textContent=arr.length}
function setSport(s){active=s;$$('.sport').forEach(b=>b.classList.toggle('active',b.dataset.sport===s));loadRemote(s)}
function normalizeEvent(e,sport){const c=e.competitions?.[0],teams=c?.competitors||[];const home=teams.find(t=>t.homeAway==='home')?.team?.displayName||'Home';const away=teams.find(t=>t.homeAway==='away')?.team?.displayName||'Away';const status=e.status?.type?.state==='in'?'LIVE':e.status?.type?.completed?'FINAL':'PRE';const clock=e.status?.type?.shortDetail||e.date?.slice(11,16)||'—';const score=status==='PRE'?'–':`${teams.find(t=>t.homeAway==='home')?.score??0} : ${teams.find(t=>t.homeAway==='away')?.score??0}`;const odds=(c?.odds||e.odds||[]).flatMap(o=>[o.moneyline?.home,o.moneyline?.away,o.moneyline?.draw].filter(v=>v!==undefined&&v!==null));return {eventId:e.id||'',sport,league:c?.league?.name||'ESPN',time:clock,home,away,score,status,odds,pass:null,value:null,market:'REAL DATA',source:'ESPN public'}}
function normalizeTSB(e,sport){const date=e.strTimestamp||`${e.dateEvent||''}T${e.strTime||'00:00:00'}`;const home=e.strHomeTeam||'Home',away=e.strAwayTeam||'Away';const hs=e.intHomeScore,as=e.intAwayScore;let status='PRE';if(e.strStatus&&/finished|ft|final/i.test(e.strStatus))status='FINAL';else if(e.strStatus&&/live|1st|2nd|3rd|period|quarter|half/i.test(e.strStatus))status='LIVE';const score=status==='PRE'?'–':`${hs??0} : ${as??0}`;return {eventId:e.idEvent||'',sport,league:e.strLeague||'TheSportsDB',time:e.strTime?.slice(0,5)||date.slice(11,16)||'—',home,away,score,status,odds:[],pass:null,value:null,market:'REAL DATA',source:'TheSportsDB free'}}
function normalizeSS(e,sport){const home=e.home_team||e.homeTeam||e.home?.name||e.teams?.home?.name||'Home';const away=e.away_team||e.awayTeam||e.away?.name||e.teams?.away?.name||'Away';const hs=e.home_score??e.homeScore??e.scores?.home;const as=e.away_score??e.awayScore??e.scores?.away;const raw=(e.status||e.state||e.match_status||'').toString().toLowerCase();let status=/live|in.?play|playing|ongoing|1st|2nd|3rd|quarter|half/.test(raw)?'LIVE':/finished|final|ft|ended/.test(raw)?'FINAL':'PRE';const time=e.start_time||e.startTime||e.date||e.utc_date||e.utcDate||'—';const score=status==='PRE'?'–':`${hs??0} : ${as??0}`;return {eventId:e.id||e.match_id||'',sport,league:e.competition_name||e.league_name||e.competition?.name||'SportScore',time:typeof time==='string'?time.slice(11,16):'—',home,away,score,status,odds:[],pass:null,value:null,market:'REAL DATA',source:'SportScore free'}}
async function fetchSport(sport){const path=ESPN[sport];if(!path)return [];try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/${path}/scoreboard`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const d=await r.json();return (d.events||[]).map(e=>normalizeEvent(e,sport))}catch(e){return []}}
async function fetchTSB(sport){const league=TSB[sport];if(!league)return [];const date=new Date();const iso=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10);try{const r=await fetch(`https://www.thesportsdb.com/api/v1/json/123/eventsday.php?d=${iso}&s=${encodeURIComponent(league)}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const j=await r.json();return (j.events||[]).map(e=>normalizeTSB(e,sport))}catch(e){return []}}
async function fetchSportScore(sport){const ss=SPORT_SCORE[sport];if(!ss)return [];try{const r=await fetch(`https://sportscore.com/api/widget/matches/?sport=${ss}&limit=50&src=vika-sports`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const j=await r.json();const rows=Array.isArray(j)?j:(j.matches||j.events||j.data||[]);return rows.map(e=>normalizeSS(e,sport)).filter(x=>x.home!=='Home'||x.away!=='Away')}catch(e){return []}}
async function loadRemote(forceSport=active){const status=$('#apiStatus');if(status){status.textContent='● Получаем реальные события…';status.className='api'}const sports=forceSport==='all'?Object.keys(ESPN):[forceSport];const results=await Promise.all(sports.map(async sport=>{const primary=await fetchSport(sport);if(primary.length)return primary;const secondary=await fetchTSB(sport);if(secondary.length)return secondary;return await fetchSportScore(sport)}));remoteEvents=results.flat();if(status){if(remoteEvents.length){status.textContent=`● REAL DATA ONLINE · ${remoteEvents.length} событий`;status.className='api ok'}else{status.textContent='● Бесплатные источники временно не ответили, fallback активен';status.className='api'}}render()}
function closeModal(){const m=$('#modal');if(m)m.classList.remove('open')}
function authOpen(mode='login'){const m=$('#authModal');if(!m)return;authMode=mode;m.classList.add('open');const n=$('#authName');if(n)n.style.display=mode==='register'?'block':'none';const t=$('#authTitle');if(t)t.textContent=mode==='register'?'Создать аккаунт':'Вход в VIKA SPORTS';const s=$('#authSubmit');if(s)s.textContent=mode==='register'?'Зарегистрироваться':'Войти';const sw=$('#authSwitch');if(sw)sw.textContent=mode==='register'?'Уже есть аккаунт? Войти':'Нет аккаунта? Зарегистрироваться';const msg=$('#authMsg');if(msg)msg.textContent=''}
function authSubmit(){const name=$('#authName')?.value.trim()||'',email=$('#authEmail')?.value.trim().toLowerCase()||'',pass=$('#authPass')?.value||'',msg=$('#authMsg');if(!email||!pass||(authMode==='register'&&!name)){if(msg)msg.textContent='Заполни все поля.';return}if(authMode==='register'){localStorage.vikaUser=JSON.stringify({name,email,pass});if(msg)msg.textContent='Beta-аккаунт сохранён в этом браузере. Входим…';setTimeout(()=>authOpen('login'),500)}else{const u=JSON.parse(localStorage.vikaUser||'null');if(!u||u.email!==email||u.pass!==pass){if(msg)msg.textContent='Аккаунт не найден или данные неверны.';return}localStorage.vikaSession='1';const modal=$('#authModal');if(modal)modal.classList.remove('open');const btn=$('#loginBtn');if(btn)btn.textContent='Vika · '+(u.name||'профиль')}}
function init(){if($('#visits')){localStorage.vikaVisits=String((+localStorage.vikaVisits||0)+1);$('#visits').textContent=localStorage.vikaVisits+' в этом браузере'}if($('#predictions'))$('#predictions').textContent=localStorage.vikaPredictions||0;if($('#wins'))$('#wins').textContent=localStorage.vikaWins||0;if($('#losses'))$('#losses').textContent=localStorage.vikaLosses||0;if($('#loginBtn'))$('#loginBtn').onclick=()=>authOpen('login');if($('#heroLogin'))$('#heroLogin').onclick=()=>authOpen('register');if($('#authSubmit'))$('#authSubmit').onclick=authSubmit;if($('#authSwitch'))$('#authSwitch').onclick=()=>authOpen(authMode==='login'?'register':'login');if($('#closeAuth'))$('#closeAuth').onclick=()=>$('#authModal').classList.remove('open');if($('#close'))$('#close').onclick=closeModal;if($('#modal'))$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};if($('#search'))$('#search').oninput=e=>{const q=e.target.value.toLowerCase();$$('.event').forEach(c=>c.style.display=c.innerText.toLowerCase().includes(q)?'':'none')};if($('#refresh'))$('#refresh').onclick=()=>loadRemote(active);if($('#settings'))$('#settings').onclick=()=>$('#settingsModal')?.classList.add('open');if($('#closeSettings'))$('#closeSettings').onclick=()=>$('#settingsModal').classList.remove('open');$$('.sport').forEach(b=>b.onclick=()=>setSport(b.dataset.sport));$$('.sport').forEach(b=>b.classList.toggle('active',b.dataset.sport===active));render();if($('#events')||$('#apiStatus')||requestedSport)loadRemote(active)}
document.addEventListener('DOMContentLoaded',init);