window.VikaBacktest=(function(){
  const KEY='vika_sports_prediction_ledger_v2';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
  const write=x=>localStorage.setItem(KEY,JSON.stringify(x));
  const clean=x=>String(x??'').trim().toLowerCase();
  const finite=x=>Number.isFinite(Number(x));
  function addPrediction(p){const a=read(),id=p.id||`${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const duplicate=a.find(x=>x.id===id);if(duplicate)return duplicate;const row={id,createdAt:new Date().toISOString(),eventId:p.eventId??null,sport:p.sport??'sport',home:p.home??null,away:p.away??null,market:p.market??'1X2',selection:p.selection??null,probability:finite(p.probability)?Number(p.probability):null,fair:p.fair??null,odds:p.odds??null,edge:p.edge??null,mode:p.mode??'prematch',status:'OPEN',result:null,won:null,finalScore:null,settledAt:null};a.push(row);write(a);return row}
  function settle(id,result,finalScore){const a=read(),i=a.findIndex(x=>x.id===id);if(i<0)return null;const x=a[i];if(x.status==='SETTLED')return x;x.status='SETTLED';x.result=result;x.won=clean(x.selection)===clean(result);x.finalScore=finalScore??null;x.settledAt=new Date().toISOString();write(a);return x}
  function settleEvent(eventId,result,finalScore){const a=read(),ids=[];for(const x of a){if(String(x.eventId??'')===String(eventId)&&x.status==='OPEN'){settle(x.id,result,finalScore);ids.push(x.id)}}return ids}
  function settleFromScore(eventId,homeScore,awayScore,finalScore){const h=Number(homeScore),a=Number(awayScore);if(!Number.isFinite(h)||!Number.isFinite(a))return[];const result=h>a?'home':a>h?'away':'draw';return settleEvent(eventId,result,finalScore??`${h} : ${a}`)}
  function stats(rows){const s=rows.filter(x=>x.status==='SETTLED'),w=s.filter(x=>x.won).length,od=s.filter(x=>finite(x.odds)&&Number(x.odds)>1),profit=od.reduce((z,x)=>z+(x.won?Number(x.odds)-1:-1),0),staked=od.length;return{total:rows.length,open:rows.filter(x=>x.status==='OPEN').length,settled:s.length,wins:w,losses:s.length-w,hitRate:s.length?w/s.length*100:null,avgOdds:od.length?od.reduce((z,x)=>z+Number(x.odds),0)/od.length:null,roi:staked?profit/staked*100:null,profit,staked,brier:s.filter(x=>finite(x.probability)).length?s.filter(x=>finite(x.probability)).reduce((z,x)=>z+Math.pow(Number(x.probability)/100-(x.won?1:0),2),0)/s.filter(x=>finite(x.probability)).length:null}}
  function summary(){return stats(read())}
  function breakdown(field){const a=read().filter(x=>x.status==='SETTLED'),groups={};for(const x of a){const key=String(x[field]??'unknown');(groups[key]??=[]).push(x)}return Object.entries(groups).map(([key,rows])=>({key,...stats(rows)})).sort((a,b)=>(b.settled||0)-(a.settled||0))}
  function calibration(){const a=read().filter(x=>x.status==='SETTLED'&&finite(x.probability)),buckets=[[50,59.999],[60,69.999],[70,79.999],[80,89.999],[90,100]];return buckets.map(([lo,hi])=>{const r=a.filter(x=>Number(x.probability)>=lo&&Number(x.probability)<=hi),w=r.filter(x=>x.won).length;return{label:`${lo}–${hi}%`,count:r.length,hit:r.length?w/r.length*100:null,expected:r.length?r.reduce((z,x)=>z+Number(x.probability),0)/r.length:null}})}
  function adaptive(){const s=read().filter(x=>x.status==='SETTLED'),n=s.length;if(n<10)return{ready:false,n,adjustment:0,reason:'Нужно минимум 10 рассчитанных прогнозов.'};const hit=s.filter(x=>x.won).length/n*100;const adjustment=hit>=65?3:hit<50?-3:hit<55?-1:0;return{ready:true,n,hitRate:hit,adjustment,reason:`На выборке ${n} прогнозов фактическая проходимость ${hit.toFixed(1)}%.`}}
  function clear(){write([])}
  return{read,addPrediction,settle,settleEvent,settleFromScore,summary,breakdown,calibration,adaptive,clear,KEY};
})();
