window.VikaDailyPick=(function(){
  const MIN_ODDS=1.60,MIN_EDGE=0.03,MIN_PROB=58,MIN_CONF=55;
  const PATHS=[
    ['football','soccer/esp.1'],['football','soccer/eng.1'],['football','soccer/ita.1'],['football','soccer/ger.1'],['football','soccer/fra.1'],['football','soccer/uefa.europa'],['football','soccer/uefa.champions'],
    ['tennis','tennis/atp'],['tennis','tennis/wta'],['basketball','basketball/nba'],['hockey','hockey/nhl']
  ];
  const SPORT={football:'⚽ ФУТБОЛ',tennis:'🎾 ТЕННИС',hockey:'🏒 ХОККЕЙ',basketball:'🏀 БАСКЕТБОЛ',mma:'🥊 MMA'};
  const $=s=>document.querySelector(s);
  const money=v=>{const n=Number(v);if(!Number.isFinite(n))return null;return n>=100?1+n/100:n<=-100?1+100/Math.abs(n):n>1?n:null};
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function fmtTime(v){const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}
  function mount(){const section=$('#picks');if(!section)return null;let box=$('#dailyPick');if(!box){section.innerHTML='<div class="section-head"><div><span class="eyebrow">VIKA DAILY · REAL DATA</span><h2>Прогноз дня</h2></div><span id="dailyPickStatus" class="muted">Проверяем актуальные матчи…</span></div><div id="dailyPick"></div>'}return $('#dailyPick')}
  function oddsOf(e){const o=e?.competitions?.[0]?.odds?.[0]||e?.odds?.[0];if(!o)return{};return{home:money(o.moneyline?.home??o.homeTeamOdds?.moneyLine??o.homeTeamOdds?.moneyline??o.homeOdds),away:money(o.moneyline?.away??o.awayTeamOdds?.moneyLine??o.awayTeamOdds?.moneyline??o.awayOdds),draw:money(o.moneyline?.draw??o.drawOdds)}}
  async function ranks(path){try{const r=await fetch(`https://site.api.espn.com/apis/v2/sports/${path}/standings`,{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json(),m=new Map();const walk=x=>{if(!x)return;if(Array.isArray(x)){x.forEach(walk);return}if(x.team){let n=Number(x.rank??x.seed);if(!Number.isFinite(n)){const s=(x.stats||[]).find(v=>/rank|seed|playoff/i.test(String(v.name||v.abbreviation||'')));n=Number(s?.value)}if(x.team.id&&Number.isFinite(n))m.set(String(x.team.id),n)}walk(x.children);walk(x.entries);walk(x.standings);walk(x.groups)};walk(d);return m}catch{return new Map()}}
  async function board(sport,path,rankMap){try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/${path}/scoreboard`,{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json();return(d.events||[]).filter(e=>e?.status?.type?.state==='pre').map(e=>{const c=e.competitions?.[0],t=c?.competitors||[],h=t.find(x=>x.homeAway==='home'),a=t.find(x=>x.homeAway==='away');if(!h||!a)return null;const hr=Number(h.rank),ar=Number(a.rank);h.rank=Number.isFinite(hr)?hr:(rankMap.get(String(h.team?.id))??null);a.rank=Number.isFinite(ar)?ar:(rankMap.get(String(a.team?.id))??null);return{e,sport,path,home:h,away:a,odds:oddsOf(e)}}).filter(Boolean)}catch{return[]}}
  async function extraCandidates(){if(!window.VikaAIEngine||!window.VikaSignalEngine)return[];const groups=await Promise.all(PATHS.map(async([sport,path])=>{const rm=await ranks(path);return board(sport,path,rm)}));const out=[];for(const group of groups){for(const x of group){const pred=window.VikaAIEngine.calculate({sport:x.sport,home:x.home,away:x.away,mode:'prematch'});if(!pred)continue;const line=x.odds[pred.selection];if(!Number.isFinite(line))continue;const quality=Number(pred.quality||0),edge=(Number(pred.probability)/100*line)-1;const ok=Number(pred.probability)>=MIN_PROB&&Number(pred.confidence)>=MIN_CONF&&quality>=2&&edge>=MIN_EDGE&&line>=MIN_ODDS;const status=ok?'SIGNAL':'WATCH';out.push({eventId:x.e.id,sport:x.sport,mode:'prematch',home:x.home.team?.displayName||x.home.team?.name,away:x.away.team?.displayName||x.away.team?.name,time:x.e.date,selection:pred.selection,probability:pred.probability,fair:pred.fair,odds:line,edge,confidence:pred.confidence,status,quality,conflict:false,lineSource:'ESPN public',reason:pred.reason,path:x.path})}}return out}
  function render(row,scanned){const box=mount();if(!box)return;if(!row){box.innerHTML=`<div class="daily-empty"><div class="daily-mark">✦</div><div><span class="eyebrow">VIKA DAILY · ${new Date().toLocaleDateString('ru-RU')}</span><h3>Сегодня Vika не публикует ставку</h3><p>Нет матча, который одновременно прошёл проверку модели, имеет актуальную линию от 1.60 и не попал в конфликт. Лучше пропуск, чем выдуманный прогноз.</p><small>Проверено событий: ${scanned} · минимальный кэф 1.60</small></div></div>`;return}
    const pick=row.selection==='home'?row.home:row.selection==='away'?row.away:'Ничья';
    const href=`match.html?sport=${encodeURIComponent(row.sport)}&eventId=${encodeURIComponent(row.eventId)}&home=${encodeURIComponent(row.home)}&away=${encodeURIComponent(row.away)}&mode=prematch`;
    const edge=`${row.edge>=0?'+':''}${(row.edge*100).toFixed(1)}%`;
    box.innerHTML=`<article class="daily-card"><div class="daily-card-top"><span class="daily-badge">🔥 ПРОГНОЗ ДНЯ</span><span>${esc(SPORT[row.sport]||row.sport)} · ${fmtTime(row.time)}</span></div><div class="daily-matchup"><div><small>МАТЧ</small><h3>${esc(row.home)}</h3><h3>${esc(row.away)}</h3><p>PREMATCH · линия и модель проверены перед публикацией</p></div><div class="daily-pick"><small>VIKA ВЫБИРАЕТ</small><strong>${esc(pick)}</strong><b>КЭФ ${Number(row.odds).toFixed(2)}</b></div></div><div class="daily-metrics"><div><span>AI probability</span><b>${Number(row.probability).toFixed(1)}%</b></div><div><span>Fair</span><b>${Number(row.fair).toFixed(2)}</b></div><div><span>Edge</span><b>${edge}</b></div><div><span>Confidence</span><b>${Number(row.confidence).toFixed(0)}%</b></div></div><div class="daily-foot"><span>Линия · ${esc(row.lineSource)} · обновлено ${new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</span><a href="${href}">Разбор матча →</a></div></article>`;
  }
  function choose(rows){return(rows||[]).filter(x=>x&&x.mode==='prematch'&&x.status==='SIGNAL'&&!x.conflict&&Number(x.odds)>=MIN_ODDS&&Number(x.edge)>=MIN_EDGE&&Number(x.probability)>=MIN_PROB&&Number(x.confidence)>=MIN_CONF).sort((a,b)=>(b.edge-a.edge)||(b.confidence-a.confidence)||(b.probability-a.probability))[0]||null}
  async function refresh(){mount();const status=$('#dailyPickStatus');if(status)status.textContent='Vika проверяет актуальные матчи, форму и линию…';try{const base=window.VikaRadar?await window.VikaRadar.scan():[];const extra=await extraCandidates();const rows=[...base,...extra];const pick=choose(rows);render(pick,rows.length);if(status)status.textContent=pick?`Проверено ${rows.length} событий · выбран 1 подтверждённый сигнал`:`Проверено ${rows.length} событий · подходящего сигнала ≥ 1.60 нет`;}catch(e){render(null,0);if(status)status.textContent='Данные временно недоступны'}}
  function start(){if(!$('#picks'))return;refresh();setInterval(refresh,120000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
  return{refresh,choose};
})();
