const q=new URLSearchParams(location.search),$=s=>document.querySelector(s),text=k=>q.get(k)||'',sport=text('sport')||'sport',eventId=text('eventId'),source=text('source')||'',homeName=text('home')||'Команда 1',awayName=text('away')||'Команда 2',status=(text('status')||'PRE').toUpperCase();
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v??'—'};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>{const n=Number.parseFloat(String(v??'').replace(',','.').replace('%',''));return Number.isFinite(n)?n:null};
function americanToDecimal(v){const n=num(v);if(n===null)return null;return n>=100?1+n/100:n<=-100?1+100/Math.abs(n):n>1?n:null}
function findStat(stats,names){const wanted=names.map(x=>x.toLowerCase());for(const s of stats||[]){const n=(s.name||s.label||s.displayName||'').toLowerCase();if(wanted.some(w=>n.includes(w)))return s.displayValue??s.value??'—'}return '—'}
function numericStat(stats,names){return num(findStat(stats,names))}
function competitors(s){return s?.header?.competitions?.[0]?.competitors||[]}
function teamStats(s){const out={home:{stats:[]},away:{stats:[]}};for(const t of s?.boxscore?.teams||[]){const side=t.homeAway==='home'?'home':'away';out[side].stats=t.statistics||[]}return out}
function renderStats(s){const t=teamStats(s),hs=t.home.stats,as=t.away.stats,rows=[['Владение',findStat(hs,['possession']),findStat(as,['possession'])],['Удары',findStat(hs,['shots']),findStat(as,['shots'])],['Удары в створ',findStat(hs,['shots on target','shotsontarget']),findStat(as,['shots on target','shotsontarget'])],['Угловые',findStat(hs,['corners']),findStat(as,['corners'])],['Фолы',findStat(hs,['fouls']),findStat(as,['fouls'])]];const el=$('#liveStats');if(el)el.innerHTML=rows.map(r=>`<div class="data-row"><span>${esc(r[0])}</span><b>${esc(r[1])} · ${esc(r[2])}</b></div>`).join('');return rows}
function renderLeaders(s){const el=$('#keyPlayers'),groups=s?.leaders||[];if(!el)return;if(!groups.length){el.innerHTML='<div class="data-row"><span>Ключевые игроки</span><b>Нет данных</b></div>';return}const out=[];for(const g of groups.slice(0,5))for(const x of(g.leaders||[]).slice(0,2))out.push(`<div class="data-row"><span>${esc(g.name||g.displayName||'Метрика')}</span><b>${esc(x.athlete?.displayName||'Игрок')} · ${esc(x.displayValue||x.value||'—')}</b></div>`);el.innerHTML=out.join('')||'<div class="data-row"><span>Ключевые игроки</span><b>Нет данных</b></div>'}
function oddsCandidates(s){const roots=[s?.pickcenter?.odds,s?.odds,s?.header?.competitions?.[0]?.odds].filter(Boolean).flat(),out={home:null,draw:null,away:null,any:null};for(const r of roots){const home=americanToDecimal(r.moneyline?.home??r.homeTeamOdds?.price??r.homeOdds),away=americanToDecimal(r.moneyline?.away??r.awayTeamOdds?.price??r.awayOdds),draw=americanToDecimal(r.moneyline?.draw??r.drawOdds);if(home&&(!out.home||home!==out.home))out.home=home;if(away&&(!out.away||away!==out.away))out.away=away;if(draw)out.draw=draw;if(!out.any){const generic=americanToDecimal(r.price);if(generic)out.any=generic}}return out}
function selectedOdds(s,selection){const o=oddsCandidates(s),sel=String(selection||'').toLowerCase();if(sel==='home'||sel==='1'||sel.includes('home'))return o.home;if(sel==='away'||sel==='2'||sel.includes('away'))return o.away;if(sel==='draw'||sel==='x'||sel.includes('draw'))return o.draw;return o.any||o.home||o.away||o.draw||null}
function renderOdds(s,selection){const o=oddsCandidates(s),chosen=selectedOdds(s,selection),el=$('#marketData');if(!el)return chosen;if(!chosen){el.innerHTML='<div class="data-row"><span>Букмекерская линия</span><b>Не подключена</b></div><div class="data-row"><span>Fair / Edge</span><b>Будет после независимой линии</b></div>'}else{const parts=[];if(o.home)parts.push(`П1 ${o.home.toFixed(2)}`);if(o.draw)parts.push(`X ${o.draw.toFixed(2)}`);if(o.away)parts.push(`П2 ${o.away.toFixed(2)}`);el.innerHTML=`<div class="data-row"><span>Линия модели</span><b>${chosen.toFixed(2)}</b></div><div class="data-row"><span>Доступная линия</span><b>${parts.join(' · ')||chosen.toFixed(2)}</b></div>`}return chosen}
function features(s){const t=teamStats(s),hs=t.home.stats,as=t.away.stats;return {shots:{home:numericStat(hs,['shots']),away:numericStat(as,['shots'])},shotsOnTarget:{home:numericStat(hs,['shots on target','shotsontarget']),away:numericStat(as,['shots on target','shotsontarget'])},possession:{home:numericStat(hs,['possession']),away:numericStat(as,['possession'])}}}
function readiness(s,f){const id=!!eventId,stats=!!(s?.boxscore?.teams||[]).length,liveFeat=[f?.shots,f?.shotsOnTarget,f?.possession].filter(x=>x?.home!==null&&x?.away!==null).length>=2,preFeat=competitors(s).filter(x=>x?.records?.length||x?.record||x?.rank).length>=2;const r=status==='LIVE'?[id,stats,liveFeat].filter(Boolean).length:[id,preFeat||stats].filter(Boolean).length;set('#dataReadiness',`${r}/3`);return r}
function standingsRanks(data){const out={};for(const group of data?.children||[]){for(const entry of group?.standings?.entries||[]){const team=entry.team||{},id=String(team.id||''),rank=num(entry.stats?.find(x=>['rank','rankchange'].includes(x.name))?.value);if(id&&rank!==null)out[id]=rank}}return out}
async function enrichPrematch(s,path){if(sport!=='football')return s;try{const r=await fetch(`https://site.api.espn.com/apis/v2/sports/soccer/${path.split('/').pop()}/standings`,{cache:'no-store'});if(!r.ok)return s;const ranks=standingsRanks(await r.json());for(const c of competitors(s)){const id=String(c.team?.id||'');if(ranks[id]!=null)c.rank=ranks[id]}return s}catch{return s}}
function modelConflict(result,s,f){if(status!=='LIVE'||!result)return false;const h=competitors(s).find(x=>x.homeAway==='home'),a=competitors(s).find(x=>x.homeAway==='away');if(!h||!a)return false;const hr=num(h.rank),ar=num(a.rank),shot=f.shotsOnTarget,shots=f.shots,poss=f.possession;if(hr===null||ar===null||!shot||!shots)return false;const liveHome=(shot.home??0)+(shots.home??0)*.35+(poss?.home??0)*.04,liveAway=(shot.away??0)+(shots.away??0)*.35+(poss?.away??0)*.04,rankFav=hr<ar?'home':ar<hr?'away':null,liveFav=liveHome>liveAway?'home':liveAway>liveHome?'away':null,conflict=!!rankFav&&!!liveFav&&rankFav!==liveFav&&Math.abs(liveHome-liveAway)>=1.5;if(conflict){const box=$('.match-conflict');if(box)box.style.display='flex'}return conflict}
function applySignal(result,odds,rdy,conflict=false,s){if(!window.VikaSignalEngine){set('#aiDecision','NO BET · SIGNAL ENGINE');return null}const signal=window.VikaSignalEngine.evaluate({prediction:result,odds,dataReadiness:rdy,quality:result?.quality||0,conflict,mode:status==='LIVE'?'live':'prematch'});set('#aiDecision',signal.label);if(signal.edge!==null&&signal.edge!==undefined)set('#edge',`${signal.edge>=0?'+':''}${(signal.edge*100).toFixed(1)}%`);if(signal.status==='SIGNAL'&&window.VikaBacktest){const ledgerId=`${eventId||'event'}:${sport}:${result.market||'1X2'}:${result.selection}`;window.VikaBacktest.addPrediction({id:ledgerId,eventId,home:s?.header?.competitions?.[0]?.competitors?.find(x=>x.homeAway==='home')?.team?.displayName||homeName,away:s?.header?.competitions?.[0]?.competitors?.find(x=>x.homeAway==='away')?.team?.displayName||awayName,sport,market:result.market||'1X2',selection:result.selection,probability:result.probability,fair:result.fair,odds,edge:signal.edge,mode:status==='LIVE'?'live':'prematch'})}return signal}
function applyModel(s,f,rdy){if(!window.VikaAIEngine){set('#modelState','ENGINE ERROR');set('#aiHeadline','Модуль VikaAI не загружен');set('#aiDecision','NO BET · ENGINE');return}const cs=competitors(s),h=cs.find(x=>x.homeAway==='home'),a=cs.find(x=>x.homeAway==='away');if(!h||!a){set('#modelState','DATA BUILDING');set('#aiHeadline','Нет полной пары участников');set('#aiDecision','NO BET · DATA INCOMPLETE');return}const mode=status==='LIVE'?'live':'prematch',result=window.VikaAIEngine.calculate({sport,home:h,away:a,stats:f,mode});if(!result){set('#modelState',mode==='prematch'?'PREMATCH · DATA BUILDING':'DATA BUILDING');set('#aiProbability','—');set('#fairOdds','—');set('#edge','—');set('#confidence','—');set('#aiHeadline',mode==='prematch'?'Недостаточно предматчевых признаков':'Недостаточно live-признаков');set('#aiText','Vika не заполняет пропуски выдуманными данными. Нужен более полный набор реальных признаков.');set('#aiDecision','NO BET · DATA INCOMPLETE');return}const name=window.VikaAIEngine.label(result.selection,{home:h.team?.displayName||homeName,away:a.team?.displayName||awayName}),odds=selectedOdds(s,result.selection),edge=window.VikaAIEngine.edge(result.probability,odds),conflict=modelConflict(result,s,f);set('#modelState',mode==='prematch'?'BETA MODEL · PREMATCH':'BETA MODEL · LIVE');set('#aiProbability',`${result.probability.toFixed(1)}%`);set('#fairOdds',result.fair?.toFixed(2)||'—');set('#edge',edge===null?'—':`${edge>=0?'+':''}${(edge*100).toFixed(1)}%`);set('#confidence',`${result.confidence.toFixed(0)}%`);set('#aiHeadline',`Модель склоняется к: ${name}`);set('#aiText',conflict?'⚠️ Live-статистика и предматчевый профиль расходятся. Vika снижает доверие и не пропускает сигнал автоматически.':result.reason);set('#modelReason',`Признаков: ${result.quality} · ${result.features.join(', ')} · beta, без утверждения о калибровке.`);renderOdds(s,result.selection);applySignal(result,odds,rdy,conflict,s)}
function finalFromSummary(s){const c=competitors(s),h=c.find(x=>x.homeAway==='home'),a=c.find(x=>x.homeAway==='away'),hs=num(h?.score),as=num(a?.score);if(hs===null||as===null)return null;const completed=s?.header?.competitions?.[0]?.status?.type?.completed===true||['FINAL','POST'].includes(String(s?.header?.competitions?.[0]?.status?.type?.name||'').toUpperCase())||status==='FINAL';return completed?{result:hs>as?'home':as>hs?'away':'draw',score:`${hs} : ${as}`} : null}
function settleFinal(s){if(!window.VikaBacktest||!eventId)return;const fin=finalFromSummary(s);if(fin)window.VikaBacktest.settleEvent(eventId,fin.result,fin.score)}
async function load(){set('#matchTitle',`${homeName} vs ${awayName}`);set('#matchMeta',`${sport.toUpperCase()} · ${status} · ${source||'REAL DATA'}`);set('#matchLeague',text('league')||'VIKA SPORTS');set('#matchScore',text('score')||'– : –');set('#matchTime',text('time')||'—');set('#matchStatus',status);const conflictBox=$('.match-conflict');if(conflictBox)conflictBox.style.display='none';if(!eventId||source!=='ESPN public'){set('#dataReadiness','0/3');set('#modelState','DATA BUILDING');set('#aiHeadline','Сигнал пока не строим');set('#aiText','У события нет идентификатора детализации из реального источника. Vika ждёт полноценные данные матча.');set('#aiDecision','NO BET · DATA INCOMPLETE');return}try{const path={football:'soccer/eng.1',basketball:'basketball/nba',hockey:'hockey/nhl',tennis:'tennis/atp',mma:'mma/ufc'}[sport];if(!path)throw Error('unsupported sport');const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/${path}/summary?event=${encodeURIComponent(eventId)}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);let s=await r.json(),cs=competitors(s),h=cs.find(x=>x.homeAway==='home'),a=cs.find(x=>x.homeAway==='away');if(h&&a){set('#matchTitle',`${h.team?.displayName||homeName} vs ${a.team?.displayName||awayName}`);set('#matchScore',`${h.score??'0'} : ${a.score??'0'}`)}if(status!=='LIVE')s=await enrichPrematch(s,path);renderStats(s);renderLeaders(s);settleFinal(s);const f=features(s),rdy=readiness(s,f);applyModel(s,f,rdy);const note=$('#sourceNote');if(note)note.textContent=`REAL DATA · ESPN summary · event ${eventId}`}catch(err){set('#dataReadiness','1/3');set('#modelState','DATA FALLBACK');set('#aiHeadline','Источник детализации временно недоступен');set('#aiText','Vika не подменяет недоступную статистику выдуманными значениями.');set('#aiDecision','NO BET · SOURCE CHECK');const note=$('#sourceNote');if(note)note.textContent='REAL DATA · базовая карточка события'}}
let liveTimer=null;document.addEventListener('DOMContentLoaded',()=>{load();if(status==='LIVE'&&eventId)liveTimer=setInterval(load,60000)});