const q=new URLSearchParams(location.search),$=s=>document.querySelector(s),text=k=>q.get(k)||'',sport=text('sport')||'sport',eventId=text('eventId'),source=text('source')||'',homeName=text('home')||'Команда 1',awayName=text('away')||'Команда 2',status=(text('status')||'PRE').toUpperCase();
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v??'—'};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>{const n=Number.parseFloat(String(v??'').replace(',','.').replace('%',''));return Number.isFinite(n)?n:null};
function findStat(stats,names){const wanted=names.map(x=>x.toLowerCase());for(const s of stats||[]){const n=(s.name||s.label||s.displayName||'').toLowerCase();if(wanted.some(w=>n.includes(w)))return s.displayValue??s.value??'—'}return '—'}
function numericStat(stats,names){return num(findStat(stats,names))}
function competitors(s){return s?.header?.competitions?.[0]?.competitors||[]}
function teamStats(s){const out={home:{stats:[]},away:{stats:[]}};for(const t of s?.boxscore?.teams||[]){const side=t.homeAway==='home'?'home':'away';out[side].stats=t.statistics||[]}return out}
function renderStats(s){const t=teamStats(s),hs=t.home.stats,as=t.away.stats,rows=[['Владение',findStat(hs,['possession']),findStat(as,['possession'])],['Удары',findStat(hs,['shots']),findStat(as,['shots'])],['Удары в створ',findStat(hs,['shots on target','shotsontarget']),findStat(as,['shots on target','shotsontarget'])],['Угловые',findStat(hs,['corners']),findStat(as,['corners'])],['Фолы',findStat(hs,['fouls']),findStat(as,['fouls'])]];const el=$('#liveStats');if(el)el.innerHTML=rows.map(r=>`<div class="data-row"><span>${esc(r[0])}</span><b>${esc(r[1])} · ${esc(r[2])}</b></div>`).join('');return rows}
function renderLeaders(s){const el=$('#keyPlayers'),groups=s?.leaders||[];if(!el)return;if(!groups.length){el.innerHTML='<div class="data-row"><span>Ключевые игроки</span><b>Нет данных</b></div>';return}const out=[];for(const g of groups.slice(0,5))for(const x of(g.leaders||[]).slice(0,2))out.push(`<div class="data-row"><span>${esc(g.name||g.displayName||'Метрика')}</span><b>${esc(x.athlete?.displayName||'Игрок')} · ${esc(x.displayValue||x.value||'—')}</b></div>`);el.innerHTML=out.join('')||'<div class="data-row"><span>Ключевые игроки</span><b>Нет данных</b></div>'}
function extractOdds(s){const roots=[s?.pickcenter?.odds,s?.odds,s?.header?.competitions?.[0]?.odds].filter(Boolean).flat();for(const r of roots){const vals=[r.moneyline?.home,r.moneyline?.away,r.homeTeamOdds?.price,r.awayTeamOdds?.price,r.homeOdds,r.awayOdds,r.price];for(const v of vals){const n=num(v);if(n&&n>1&&n<100)return n}}return null}
function renderOdds(s){const o=extractOdds(s),el=$('#marketData');if(!el)return o;if(!o){el.innerHTML='<div class="data-row"><span>Букмекерская линия</span><b>Не подключена</b></div><div class="data-row"><span>Fair / Edge</span><b>Будет после независимой линии</b></div>'}else el.innerHTML=`<div class="data-row"><span>Коэффициент</span><b>${o.toFixed(2)}</b></div><div class="data-row"><span>Источник линии</span><b>Данные события</b></div>`;return o}
function features(s){const t=teamStats(s),hs=t.home.stats,as=t.away.stats;return {shots:{home:numericStat(hs,['shots']),away:numericStat(as,['shots'])},shotsOnTarget:{home:numericStat(hs,['shots on target','shotsontarget']),away:numericStat(as,['shots on target','shotsontarget'])},possession:{home:numericStat(hs,['possession']),away:numericStat(as,['possession'])}}}
function readiness(s,f){const id=!!eventId,stats=!!(s?.boxscore?.teams||[]).length,feat=sport==='football'?[f?.shots,f?.shotsOnTarget,f?.possession].filter(x=>x?.home!==null&&x?.away!==null).length>=2:competitors(s).every(x=>num(x.score)!==null),r=[id,stats,feat].filter(Boolean).length;set('#dataReadiness',`${r}/3`);return r}
function applySignal(result,odds,rdy,conflict=false){if(!window.VikaSignalEngine){set('#aiDecision','NO BET · SIGNAL ENGINE');return null}const signal=window.VikaSignalEngine.evaluate({prediction:result,odds,dataReadiness:rdy,quality:result?.quality||0,conflict,mode:status==='LIVE'?'live':'prematch'});set('#aiDecision',signal.label);if(signal.edge!==null&&signal.edge!==undefined)set('#edge',`${signal.edge>=0?'+':''}${(signal.edge*100).toFixed(1)}%`);if(signal.status==='SIGNAL'&&window.VikaBacktest){const ledgerId=`${eventId||'event'}:${sport}:${result.selection}`;window.VikaBacktest.addPrediction({id:ledgerId,sport,selection:result.selection,probability:result.probability,fair:result.fair,odds,edge:signal.edge,mode:status==='LIVE'?'live':'prematch'})}return signal}
function applyModel(s,f,rdy){if(!window.VikaAIEngine){set('#modelState','ENGINE ERROR');set('#aiHeadline','Модуль VikaAI не загружен');set('#aiDecision','NO BET · ENGINE');return}const cs=competitors(s),h=cs.find(x=>x.homeAway==='home'),a=cs.find(x=>x.homeAway==='away');if(!h||!a){set('#modelState','DATA BUILDING');set('#aiHeadline','Нет полной пары участников');set('#aiDecision','NO BET · DATA INCOMPLETE');return}const mode=status==='LIVE'?'live':'prematch',result=window.VikaAIEngine.calculate({sport,home:h,away:a,stats:f,mode});if(!result){set('#modelState',mode==='prematch'?'PREMATCH · DATA BUILDING':'DATA BUILDING');set('#aiProbability','—');set('#fairOdds','—');set('#edge','—');set('#confidence','—');set('#aiHeadline',mode==='prematch'?'Недостаточно предматчевых признаков':'Недостаточно live-признаков');set('#aiText','Vika не заполняет пропуски выдуманными данными. Нужен более полный набор реальных признаков.');set('#aiDecision','NO BET · DATA INCOMPLETE');return}const name=window.VikaAIEngine.label(result.selection,{home:h.team?.displayName||homeName,away:a.team?.displayName||awayName}),odds=extractOdds(s),edge=window.VikaAIEngine.edge(result.probability,odds);set('#modelState',mode==='prematch'?'BETA MODEL · PREMATCH':'BETA MODEL · LIVE');set('#aiProbability',`${result.probability.toFixed(1)}%`);set('#fairOdds',result.fair?.toFixed(2)||'—');set('#edge',edge===null?'—':`${edge>=0?'+':''}${(edge*100).toFixed(1)}%`);set('#confidence',`${result.confidence.toFixed(0)}%`);set('#aiHeadline',`Модель склоняется к: ${name}`);set('#aiText',result.reason);set('#modelReason',`Признаков: ${result.quality} · ${result.features.join(', ')} · beta, без утверждения о калибровке.`);applySignal(result,odds,rdy,false)}
async function load(){set('#matchTitle',`${homeName} vs ${awayName}`);set('#matchMeta',`${sport.toUpperCase()} · ${status} · ${source||'REAL DATA'}`);set('#matchLeague',text('league')||'VIKA SPORTS');set('#matchScore',text('score')||'– : –');set('#matchTime',text('time')||'—');set('#matchStatus',status);if(!eventId||source!=='ESPN public'){set('#dataReadiness','0/3');set('#modelState','DATA BUILDING');set('#aiHeadline','Сигнал пока не строим');set('#aiText','У события нет идентификатора детализации из реального источника. Vika ждёт полноценные данные матча.');set('#aiDecision','NO BET · DATA INCOMPLETE');return}try{const path={football:'soccer/eng.1',basketball:'basketball/nba',hockey:'hockey/nhl',tennis:'tennis/atp',mma:'mma/ufc'}[sport];if(!path)throw Error('unsupported sport');const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/${path}/summary?event=${encodeURIComponent(eventId)}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const s=await r.json(),cs=competitors(s),h=cs.find(x=>x.homeAway==='home'),a=cs.find(x=>x.homeAway==='away');if(h&&a){set('#matchTitle',`${h.team?.displayName||homeName} vs ${a.team?.displayName||awayName}`);set('#matchScore',`${h.score??'0'} : ${a.score??'0'}`)}renderStats(s);renderLeaders(s);renderOdds(s);const f=features(s),rdy=readiness(s,f);if(rdy<3&&status!=='LIVE'){set('#aiHeadline','Предматчевый сигнал пока не публикуем');set('#aiText','Событие подтверждено, но независимых предматчевых признаков недостаточно.')}applyModel(s,f,rdy);const note=$('#sourceNote');if(note)note.textContent=`REAL DATA · ESPN summary · event ${eventId}`}catch(err){set('#dataReadiness','1/3');set('#modelState','DATA FALLBACK');set('#aiHeadline','Источник детализации временно недоступен');set('#aiText','Vika не подменяет недоступную статистику выдуманными значениями.');set('#aiDecision','NO BET · SOURCE CHECK');const note=$('#sourceNote');if(note)note.textContent='REAL DATA · базовая карточка события'}}
document.addEventListener('DOMContentLoaded',load);