window.VikaRadar=(function(){
  const ESPN={football:'soccer/eng.1',tennis:'tennis/atp',basketball:'basketball/nba',hockey:'hockey/nhl',mma:'mma/ufc'};
  const LABEL={football:'Футбол',tennis:'Теннис',basketball:'Баскетбол',hockey:'Хоккей',mma:'MMA'};
  const money=v=>{const n=Number(v);if(!Number.isFinite(n))return null;return n>=100?1+n/100:n<=-100?1+100/Math.abs(n):n>1?n:null};
  const rank=c=>{const n=Number(c?.rank??c?.ranking?.rank);return Number.isFinite(n)?n:null};
  const odds=o=>{if(!o)return{};return{home:money(o.moneyline?.home??o.homeTeamOdds?.moneyLine??o.homeTeamOdds?.price??o.homeOdds),away:money(o.moneyline?.away??o.awayTeamOdds?.moneyLine??o.awayTeamOdds?.price??o.awayOdds),draw:money(o.moneyline?.draw??o.drawOdds)}};
  async function fetchSport(sport){try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/${ESPN[sport]}/scoreboard`,{cache:'no-store'});if(!r.ok)throw 0;return(await r.json()).events||[]}catch{return[]}}
  async function fetchRanks(sport){try{const r=await fetch(`https://site.api.espn.com/apis/v2/sports/${ESPN[sport]}/standings`,{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json(),m=new Map();const walk=x=>{if(!x)return;if(Array.isArray(x)){x.forEach(walk);return}if(x.team){let n=Number(x.rank??x.seed);const stats=x.stats||[];if(!Number.isFinite(n)){const s=stats.find(v=>/rank|seed|playoff/i.test(String(v.name||v.abbreviation||'')));n=Number(s?.value)}if(x.team.id&&Number.isFinite(n))m.set(String(x.team.id),n)}walk(x.children);walk(x.entries);walk(x.standings);walk(x.groups)};walk(d);return m}catch{return new Map()}}
  async function fetchSummary(sport,eventId){try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/${ESPN[sport]}/summary?event=${encodeURIComponent(eventId)}`,{cache:'no-store'});if(!r.ok)throw 0;return await r.json()}catch{return null}}
  function eventMode(e){return e?.status?.type?.state==='in'?'live':'prematch'}
  function statNumber(stats,names){for(const s of stats||[]){const n=String(s?.name||s?.label||s?.displayName||'').toLowerCase();if(names.some(x=>n.includes(x))){const v=Number(String(s?.value??s?.displayValue??'').replace('%',''));if(Number.isFinite(v))return v}}return null}
  function liveStats(summary){const out={shots:{home:null,away:null},shotsOnTarget:{home:null,away:null},possession:{home:null,away:null}};for(const t of summary?.boxscore?.teams||[]){const side=t.homeAway==='home'?'home':'away',s=t.statistics||[];out.shots[side]=statNumber(s,['shots']);out.shotsOnTarget[side]=statNumber(s,['shots on target','shotsontarget']);out.possession[side]=statNumber(s,['possession'])}return out}
  function summaryOdds(summary){const roots=[summary?.pickcenter?.odds,summary?.odds,summary?.header?.competitions?.[0]?.odds].filter(Boolean).flat();for(const r of roots){const o=odds(r);if(o.home||o.away||o.draw)return o}return{}}
  async function model(e,sport,ranks,summary){
    const c=e?.competitions?.[0],t=c?.competitors||[],h=t.find(x=>x.homeAway==='home'),a=t.find(x=>x.homeAway==='away');if(!h||!a||!window.VikaAIEngine||!window.VikaSignalEngine)return null;
    const hr=rank(h)??ranks.get(String(h.team?.id)),ar=rank(a)??ranks.get(String(a.team?.id));
    if(hr!=null)h.rank=hr;if(ar!=null)a.rank=ar;
    const mode=eventMode(e);
    if(mode==='live'&&!['football','tennis'].includes(sport))return null;
    const stats=mode==='live'&&sport==='football'?liveStats(summary):null;
    const prediction=window.VikaAIEngine.calculate({sport,home:h,away:a,stats,mode});
    if(!prediction)return null;
    const boardOdds=odds(c.odds?.[0]||e.odds?.[0]),sumOdds=summaryOdds(summary),available={...boardOdds,...Object.fromEntries(Object.entries(sumOdds).filter(([,v])=>v!=null))},line=available[prediction.selection];
    const quality=Number(prediction.quality||0),readiness=mode==='live'&&sport==='football'?(quality>=3?3:quality>=2?2:1):(quality>=2?3:Math.min(2,quality+1));
    const signal=window.VikaSignalEngine.evaluate({prediction,odds:line,dataReadiness:readiness,quality,conflict:false,mode});
    return{eventId:e.id,sport,mode,home:h.team?.displayName||'Home',away:a.team?.displayName||'Away',time:e.date,selection:prediction.selection,probability:prediction.probability,fair:prediction.fair,odds:line??null,edge:signal.edge??null,confidence:prediction.confidence,status:signal.status==='SIGNAL'?'SIGNAL':'WATCH',reason:signal.reason,modelReason:prediction.reason,liveStats:stats};
  }
  function draw(rows,meta){const box=document.querySelector('#radarResults'),metaBox=document.querySelector('#radarMeta');if(!box)return;const signals=rows.filter(x=>x.status==='SIGNAL'),watch=rows.filter(x=>x.status==='WATCH');if(metaBox)metaBox.textContent=`Последний скан: ${new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})} · проверено ${meta.scanned} · LIVE stats ${meta.liveStats} · SIGNAL ${signals.length} · WATCH ${watch.length}`;if(!rows.length){box.innerHTML='<div class="radar-empty">Пока нет матчей, которые можно корректно проверить. Vika ничего не выдумывает.</div>';return}box.innerHTML=rows.slice(0,10).map(x=>{const edge=x.edge==null?'нет линии':`${x.edge>=0?'+':''}${(x.edge*100).toFixed(1)}%`;const q=x.selection==='home'?x.home:x.selection==='away'?x.away:'Ничья';const href=`match.html?sport=${encodeURIComponent(x.sport)}&eventId=${encodeURIComponent(x.eventId)}&home=${encodeURIComponent(x.home)}&away=${encodeURIComponent(x.away)}&mode=${encodeURIComponent(x.mode)}`;return `<article class="radar-row"><div><span class="radar-status ${x.status.toLowerCase()}">${x.status==='SIGNAL'?'🔥 SIGNAL':'👁 WATCH'}</span><b>${x.home} · ${x.away}</b><small>${q} · ${LABEL[x.sport]||x.sport} · ${x.mode==='live'?'LIVE':'PREMATCH'}${x.liveStats?' · live stats':''}</small></div><div class="radar-metrics"><span>AI <b>${x.probability.toFixed(1)}%</b></span><span>Fair <b>${x.fair.toFixed(2)}</b></span><span>Edge <b>${edge}</b></span><span>Conf <b>${x.confidence.toFixed(0)}%</b></span></div><a href="${href}">Открыть →</a></article>`}).join('')}
  async function scan(){const sports=Object.keys(ESPN),meta={scanned:0,liveStats:0},results=await Promise.all(sports.map(async sport=>{const events=await fetchSport(sport),ranks=await fetchRanks(sport);return Promise.all(events.map(async e=>{meta.scanned++;const live=eventMode(e)==='live'&&['football','tennis'].includes(sport),summary=live?await fetchSummary(sport,e.id):null;if(summary?.boxscore?.teams?.length)meta.liveStats++;return model(e,sport,ranks,summary)}))}));const rows=results.flat().filter(Boolean);rows.sort((a,b)=>(b.status==='SIGNAL')-(a.status==='SIGNAL')||(b.mode==='live')-(a.mode==='live')||(b.edge??-999)-(a.edge??-999)||b.confidence-a.confidence);draw(rows,meta);return rows}
  document.addEventListener('DOMContentLoaded',()=>{if(document.querySelector('#radarResults')){scan();setInterval(scan,120000)}});return{scan};
})();
