(function(){
  const ESPN={football:'soccer/eng.1',basketball:'basketball/nba',hockey:'hockey/nhl',tennis:'tennis/atp',mma:'mma/ufc'};
  const moneyToDecimal=v=>{const n=Number(v);if(!Number.isFinite(n))return null;return n>=100?1+n/100:n<=-100?1+100/Math.abs(n):n>1?n:null};
  const parseRecord=c=>{const list=Array.isArray(c?.records)?c.records:[c?.records||c?.record];for(const r of list){const s=String(r?.summary||r?.displayValue||'');const m=s.match(/(\d+)\s*[-:]\s*(\d+)/);if(m){const w=Number(m[1]),l=Number(m[2]);if(w+l)return w/(w+l)}}return null};
  const rankOf=c=>{const n=Number(c?.rank??c?.ranking?.rank);return Number.isFinite(n)?n:null};
  function extractOdds(o){if(!o)return {};const home=o.moneyline?.home??o.homeTeamOdds?.moneyLine??o.homeTeamOdds?.moneyline??o.homeOdds,away=o.moneyline?.away??o.awayTeamOdds?.moneyLine??o.awayTeamOdds?.moneyline??o.awayOdds,draw=o.moneyline?.draw??o.drawOdds;return {home:moneyToDecimal(home),away:moneyToDecimal(away),draw:moneyToDecimal(draw)}}
  function calcFootball(home,away,odds){
    const hw=parseRecord(home),aw=parseRecord(away),hr=rankOf(home),ar=rankOf(away),features=[];
    if(hw!=null&&aw!=null)features.push('form');if(hr!=null&&ar!=null)features.push('ranking');
    if(features.length<2)return null;
    let score=(hw-aw)*2.6+(ar-hr)/20*.55+.22;
    const sig=x=>1/(1+Math.exp(-Math.max(-8,Math.min(8,x))));
    const h=Math.max(8,Math.min(86,sig(score)*100)),a=Math.max(8,Math.min(86,(1-sig(score))*100)),d=Math.max(9,Math.min(24,22-Math.abs(score)*3)),scale=100/(h+a+d),p={home:h*scale,draw:d*scale,away:a*scale};
    const top=Object.entries(p).sort((x,y)=>y[1]-x[1])[0],prob=top[1],fair=100/prob,odd=odds?.[top[0]]??null,edge=odd?prob/100*odd-1:null;
    const confidence=Math.min(88,Math.max(58,52+features.length*5)),status=odd&&edge>=.03&&prob>=55&&confidence>=60?'SIGNAL':'WATCH';
    return {selection:top[0],probability:prob,fair,odds:odd,edge,confidence,status,features};
  }
  function calcTennis(home,away){const hw=parseRecord(home),aw=parseRecord(away);if(hw==null||aw==null)return null;const score=(hw-aw)*3,p0=1/(1+Math.exp(-Math.max(-8,Math.min(8,score))))*100,prob=Math.max(10,Math.min(90,Math.max(p0,100-p0)));return {selection:p0>=50?'home':'away',probability:prob,fair:100/prob,odds:null,edge:null,confidence:58,status:'WATCH',features:['form']};}
  async function load(sport){const path=ESPN[sport];if(!path)return new Map();try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/${path}/scoreboard`,{cache:'no-store'});if(!r.ok)return new Map();const d=await r.json();return new Map((d.events||[]).map(e=>[String(e.id),e]));}catch{return new Map()}}
  async function standings(sport){const path=ESPN[sport];if(!path)return new Map();try{const r=await fetch(`https://site.api.espn.com/apis/v2/sports/${path}/standings`,{cache:'no-store'});if(!r.ok)return new Map();const d=await r.json(),map=new Map();const rankFromEntry=e=>{const stats=e?.stats||[];for(const s of stats){const key=String(s.name||s.abbreviation||'').toLowerCase();if(['rank','ranking','playoffseed','seed'].includes(key)){const n=Number(s.value);if(Number.isFinite(n))return n}}const n=Number(e?.seed??e?.rank);return Number.isFinite(n)?n:null};const walk=node=>{if(!node)return;if(Array.isArray(node)){node.forEach(walk);return}if(node.team){const id=String(node.team.id??node.team.uid??'');const rank=rankFromEntry(node);if(id&&rank!=null)map.set(id,rank)}if(node.entry){const id=String(node.entry.team?.id??node.entry.team?.uid??'');const rank=rankFromEntry(node.entry);if(id&&rank!=null)map.set(id,rank)}walk(node.children);walk(node.entries);walk(node.standings);walk(node.groups)};walk(d);return map}catch{return new Map()}}
  function decorate(card,e,sport,rankMap){const c=e?.competitions?.[0],teams=c?.competitors||[];const home=teams.find(x=>x.homeAway==='home'),away=teams.find(x=>x.homeAway==='away');if(!home||!away)return;home.rank=home.rank??rankMap.get(String(home.team?.id));away.rank=away.rank??rankMap.get(String(away.team?.id));
    const o=(c.odds||e.odds||[])[0],odds=extractOdds(o);
    const ai=sport==='football'?calcFootball(home,away,odds):sport==='tennis'?calcTennis(home,away):null;if(!ai)return;const row=card.querySelector('.chips');if(!row)return;
    const label=ai.status==='SIGNAL'?'🔥 SIGNAL':'👁 WATCH';const edge=ai.edge!=null?`<span class="value">Edge ${ai.edge>=0?'+':''}${(ai.edge*100).toFixed(1)}%</span>`:'';const line=ai.odds?`<span>Кэф <b>${ai.odds.toFixed(2)}</b></span>`:'';row.innerHTML=`<span>VikaAI ${ai.probability.toFixed(1)}%</span><span>Fair <b>${ai.fair.toFixed(2)}</b></span><span>Confidence <b>${ai.confidence}%</b></span>${line}${edge}<span class="vika-status ${ai.status.toLowerCase()}">${label}</span>`;
    card.dataset.confidence=ai.confidence;card.dataset.edge=ai.edge!=null?ai.edge*100:-999;
  }
  async function enhance(){const cards=[...document.querySelectorAll('.event')];if(!cards.length)return;const groups={};cards.forEach(card=>{const href=card.querySelector('a[href*="eventId="]')?.getAttribute('href')||'';const qs=new URLSearchParams(href.split('?')[1]||''),id=qs.get('eventId'),sport=qs.get('sport');if(id&&sport)(groups[sport]??=[]).push([id,card])});for(const sport of Object.keys(groups)){const [map,rankMap]=await Promise.all([load(sport),sport==='football'?standings(sport):Promise.resolve(new Map())]);groups[sport].forEach(([id,card])=>decorate(card,map.get(String(id)),sport,rankMap));}}
  document.addEventListener('vika:data-loaded',()=>setTimeout(enhance,50));document.addEventListener('DOMContentLoaded',()=>setTimeout(enhance,500));window.VikaCards={enhance};
})();